### ISSUE TITLE
missing ontology license

### ISSUE THREAD

**Issue by egonw** [semanticchemistry/semanticchemistry#31]
reported by OBO: http://obo-dashboard-test.ontodev.com/cheminf/dashboard.html

![image](https://user-images.githubusercontent.com/26721/75229416-25e85600-57b2-11ea-8e4a-f8d448e03063.png)

**Comment by StroemPhi** [comment]
new dashboard link: http://dashboard.obofoundry.org/dashboard/cheminf/dashboard.html

**Comment by egonw** [comment]
thanks!

**Comment by egonw** [comment]
License predicate will be updated soon.

**Comment by egonw** [comment]
Should be okay now, after #48
