### ISSUE TITLE
Wrong PURL in CHEMINF

### ISSUE THREAD

**Issue by matentzn** [semanticchemistry/semanticchemistry#35]
Hey! In our great [OBO wide effort to fix our PURLs](https://github.com/orgs/OBOFoundry/projects/5), I noticed the following wrong ones being used in CHEMINF:

http://purl.obolibrary.org/obo#is_enantiomer_of

**Comment by StroemPhi** [comment]
same seems to hold for: http://purl.obolibrary.org/obo#is_tautomer_of

**Comment by batchelorc** [comment]
These are from ChEBI from some time ago so probably best to see what ChEBI is doing nowadays.

**Comment by egonw** [comment]
- http://purl.obolibrary.org/obo/chebi#is_enantiomer_of 
- http://purl.obolibrary.org/obo/chebi#is_tautomer_of

**Comment by egonw** [comment]
@jmillanacosta, can you perhaps make a patch to update the URLs? See https://github.com/semanticchemistry/semanticchemistry/blob/0eb01cbe921c79088823c7c2b1e1e430fa26fc15/ontology/cheminf.owl#L262-L283
