### ISSUE TITLE
Representing CHEMINF in the Bioregistry

### ISSUE THREAD

**Issue by cthoyt** [semanticchemistry/semanticchemistry#41]
The [Bioregistry](https://github.com/biopragmatics/bioregistry) is a registry of prefixes and their associated metadata (it accomplishes the same goals as Identifiers.org, but it's completely open source). It additionally has a slew of manual, automated, and semi-automated tools for mapping to external registries like Identifiers.org, N2T, etc. that list additional metadata about prefixes. 

CHEMINF curates information about identifiers as children of [IAO_0000577](https://www.ebi.ac.uk/ols/ontologies/cheminf/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000577&viewMode=All&siblings=false) and is therefore of interest. In https://github.com/biopragmatics/bioregistry/pull/255, I've implemented automatic alignment and curation sheet generation for CHEMINF in the Bioregistry. I was able to match several of the entries here, but the following 7 remain:

cheminf_id	| name	| description | Issue/comment
-----|------|------|--------|
000234	| PubChem conformer	| None | This seems like something that's only locally useful given a CID and there isn't an endpoint that resolves them
000303	| GenBank Protein Identifier |	None | Could this be the same as NCBIProtein?
000447	| European Community number |	A seven-digit identifier for chemical substances for regulatory purposes within the European Union. | https://github.com/biopragmatics/bioregistry/issues/257
000467	| validated chemical database	| None
000565	| National Service Center number	| Identifier used by the Cancer Chemotherapy National Service Center. | https://github.com/biopragmatics/bioregistry/issues/258 |
000566	| RTECS	| Identifier used by the RTECS database (http://www.cdc.gov/niosh/rtecs/). | Seems like RTECS is a proprietary database. Not sure why it's in the ontology, this isn't generally useful

Would anyone be able to help give a bit more information about what some of these are and why they're in CHEMINF? E.g., I am familiar with PubChem, but don't really know what a PubChem conformer idea is. Same for the rest (except RTECS, which I haven't looked into via that link yet)

If you want to request a new prefix in the Bioregistry, you can do so with this GitHub issue template: https://github.com/biopragmatics/bioregistry/issues/new?assignees=cthoyt&labels=New%2CPrefix&template=new-prefix.yml&title=Add+prefix+%5BX%5D

**Comment by cthoyt** [comment]
@egonw can you comment on this?

**Comment by egonw** [comment]
Intuitively, I would say, most of these are not worth the effort right now. Perhaps except for the last one?

About why, I can look up late who added it (`git blame`) and figure out the context, but it's not high on my last, I'm afraid.
