### ISSUE TITLE
Missing entry - CHEMINF_000062

### ISSUE THREAD

**Issue by stuchalk** [semanticchemistry/semanticchemistry#43]
The following link resolves correctly https://semanticscience.org/resource/CHEMINF_000062 to a page indicating the representation of a 'bond order' descriptor.  However, loading http://semanticscience.org/ontology/cheminf.owl this term is not present.  Am I missing something or does it need to be added (or undeleted...)?

**Comment by StroemPhi** [comment]
Using the GH search for this repo I using ["bond order descriptor"](https://github.com/semanticchemistry/semanticchemistry/search?q=bond+order+descriptor) leads to it being declared in [cheminf-core.owl](https://github.com/semanticchemistry/semanticchemistry/blob/master/ontology/cheminf-core.owl). So the app with which you are loading [cheminf.owl](http://semanticscience.org/ontology/cheminf.owl) doesn't seem to be loading its direct imports. 

I think this is a good example of why direct imports should better be merged in a "full" relesae artefact (see also: https://oboacademy.github.io/obook/reference/release-artefacts/#release-artefact-2-full-required).

**Comment by egonw** [comment]
Yes, it's defined here: https://github.com/semanticchemistry/semanticchemistry/blob/2d512aa9440803083bfc7a9926d72d97f8325ced/ontology/cheminf-core.owl#L1174-L1186
