### ISSUE TITLE
change to the CCZero International license

### ISSUE THREAD

**Issue by egonw** [semanticchemistry/semanticchemistry#47]
Currently, the license is a CC-BY-SA license. The proposal is to change this to a more common CC-BY 4.0 International license. See also https://github.com/semanticchemistry/semanticchemistry/pull/44#issuecomment-1193995517

All contributors, please reply to this issue or be emailing me if you approve of this change.

Ping @batchelorc @olas @muntisa @micheldumontier @steinbeck

**Comment by egonw** [comment]
I approve of the change.

**Comment by micheldumontier** [comment]
Wikidata requires Cc-0 / public license.  should we consider that instead?

**Comment by egonw** [comment]
> Wikidata requires Cc-0 / public license. should we consider that instead?

Ah, good one. For data I would have agreed, but for ontologies I think it should be fine:

1. the ontology can still be integrated based on the identifiers
2. the hierarchy is harder to integrate, even between ontologies. Wikidata does not use an upper ontology, and with alignment with Wikipedia is hard to structure.
3. the license we pick only applies to the unique parts and not the things we reuse

Thoughts?

**Comment by jannahastings** [comment]
I absolutely agree to the more permissive license.

**Comment by steinbeck** [comment]
Agreed. 

Cheers, 

Chris

— 
Prof. Dr. Christoph Steinbeck
Analytical Chemistry - Cheminformatics and Chemometrics
Friedrich-Schiller-University Jena, Germany
Phone Secretariat: +49-3641-948171
http://cheminf.uni-jena.de
http://orcid.org/0000-0001-6966-0814

What is man but that lofty spirit - that sense of enterprise.
... Kirk, "I, Mudd," stardate 4513.3..

**Comment by olas** [comment]
I also agree.
Ola

**Comment by micheldumontier** [comment]
then let's go for CC-0. then the whole of the ontology (that we are responsible for) can also be added to wikidata and be used by any organisation for any purpose.

**Comment by egonw** [comment]
Yes, everyone seems okay with that. I am awaiting one more answer.

**Comment by batchelorc** [comment]
Is that me? I approve.

**Comment by egonw** [comment]
@StroemPhi, are you okay with CCZero too?

**Comment by StroemPhi** [comment]
@egonw, didn't know my opinion was needed, but sure, am all for team open science 🚀

**Comment by egonw** [comment]
Transition completed.
