### ISSUE TITLE
CHEMINF resolution to move from semanticscience resolver to Ontobee

### ISSUE THREAD

**Issue by micheldumontier** [semanticchemistry/semanticchemistry#59]
Owing to end-of-life support for PHP 7, there are strict requirements on PHP code such that the semanticscience ontology resolution service will no longer function owing to a lack of update in its library dependencies. For this reason, we have decided to forward CHEMINF IRI resolution requests to Ontobee, where the high level ontology page is 
https://ontobee.org/ontology/CHEMINF
and individual concept resolution pages are available, for instance 
https://ontobee.org/ontology/CHEMINF?iri=http://semanticscience.org/resource/CHEMINF_000550

ontobee also offers rdf descriptions of these concepts with content type negotation and with links:
https://ontobee.org/ontology/rdf/CHEMINF?iri=http://semanticscience.org/resource/CHEMINF_000550

ontobee also has a SPARQL endpoint for all the ontologies, which is really nice, and you can see an example of querying for a CHEMINF concept using yasgui:
https://api.triplydb.com/s/UKbhkRgEW

we'll be putting this into production shortly, but any questions or comments are welcome.

**Comment by micheldumontier** [comment]
@egonw

**Comment by egonw** [comment]
@micheldumontier, is there anything we need to do on the CHEMINF side? Do we want to keep the current IRIs? I think you suggest yes, correct?

**Comment by micheldumontier** [comment]
@egonw we have now switched to ontobee for CHEMINF. 

[http://semanticscience.org/resource/CHEMINF_000550](http://semanticscience.org/resource/CHEMINF_000550)

nothing needs to be done.

cheers,

m.
